// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dssksjomafwstswvzgqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzc2tzam9tYWZ3c3Rzd3Z6Z3FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDAzMTcsImV4cCI6MjA2OTE3NjMxN30.ewrrL4i0xOZMsj04dDpNzBlIjpCEzLLVhoK6fNIxwhU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});